# Generated by Django 3.2.4 on 2021-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedMatch', '0003_auto_20210627_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description_file', models.FileField(upload_to='')),
                ('description_category', models.CharField(choices=[('MT', 'Matches'), ('PR', 'Predictions')], default='', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='MatchDescriptions',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='prediction_description',
            new_name='prediction_file',
        ),
    ]
