# Generated by Django 3.2.4 on 2021-06-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FixedMatch', '0004_auto_20210627_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdescription',
            old_name='description_category',
            new_name='category',
        ),
    ]
