# Generated by Django 3.2.4 on 2021-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedMatch', '0006_user_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
