# Generated by Django 3.2.5 on 2021-07-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FixedMatch', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
