# Generated by Django 3.2.4 on 2021-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedMatch', '0005_rename_description_category_matchdescription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
